name: "rtl_433"
description: "Home Assistant version of rtl_443 to MQTT"
version: "1.0.0"
slug: "rtl_433_slug"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
boot: manual
startup: once
video: false
init: false
host_network: true
options:
  rtl_options: " "
  mqtt_server: "localhost"
  mqtt_port: 1883
  mqtt_user: "user"
  mqtt_password: "password"
schema:
  rtl_options: str
  mqtt_server: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
usb: true
startup: once
init: false
